DATA CLEANING:

# Importing The Dataset

In [136]:
import pandas as pd
from pathlib import Path

BASE = Path.cwd()
data = pd.read_csv(BASE / 'archive (1)' / 'Airbnb_Open_Data.csv')

#^CHECK ALL THE COLUMNS:
(data.columns)

C:\Users\akaii\AppData\Local\Temp\ipykernel_23356\1601250203.py:5: DtypeWarning: Columns (25: license) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(BASE / 'archive (1)' / 'Airbnb_Open_Data.csv')

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

# Creating Two Columns For Keeping And Dropping

In [137]:
#& delete the redundant columns:
columnsToKeep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columnsToDrop = ['id','reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

In [138]:
len(columnsToKeep)

19

In [139]:
len(columnsToDrop)

7

# 1st Method, Filtering Data

In [140]:
df = data[columnsToKeep]

# 2nd Method, Dropping Columns

In [141]:
data.drop(columns=columnsToDrop, inplace=True)

# Renaming The Columns

In [142]:
data.rename(columns={'NAME' : 'Name'}, inplace=True)

# 2nd Method Of Renaming Columns

In [143]:
newColumnNames = []
for i in data.columns:
    newColumnNames.append(i.upper())

In [144]:
newColumnNames

['NAME',
 'HOST ID',
 'HOST_IDENTITY_VERIFIED',
 'HOST NAME',
 'NEIGHBOURHOOD GROUP',
 'NEIGHBOURHOOD',
 'LAT',
 'LONG',
 'COUNTRY',
 'COUNTRY CODE',
 'INSTANT_BOOKABLE',
 'CANCELLATION_POLICY',
 'ROOM TYPE',
 'CONSTRUCTION YEAR',
 'PRICE',
 'SERVICE FEE',
 'MINIMUM NIGHTS',
 'NUMBER OF REVIEWS',
 'LAST REVIEW']

In [145]:
#This copies the already modified (19 columns) data frame.
newDataframeToModify = data.copy()
#This copies the upper case names from newColumnNames
newDataframeToModify.columns = newColumnNames
#This prints the new Dataframe with upper case letters
newDataframeToModify.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='str')

# Data Duplication Techniques

In [146]:
#Prints whether the first 5 of the series are duplicated
data.duplicated().head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [54]:
#Prints whether the last 5 of the series are duplicated
data.duplicated().tail()

102594    True
102595    True
102596    True
102597    True
102598    True
dtype: bool

In [ ]:
#This checks how many total are duplicated and how many aren't
data.duplicated().value_counts()

np.int64(541)

In [147]:
#This will create the data frame with no duplicates and will make a new dataframe.
data.drop_duplicates(inplace=True)

In [148]:
#0 in the output shows that the dataframe has no duplicates left.
data.duplicated().sum()

np.int64(0)

# Remove The NAN Values From The Dataset

In [149]:
data.isna().sum()

Name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
Construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

# Drop All The NAN Values And Modify The DataFrame

In [150]:
data.dropna(inplace=True)
data.isna().sum()

Name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
Construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
last review               0
dtype: int64

# Cleaning Individual Columns

In [151]:
#This will make all the entries in the column uppercase
data['host_identity_verified'].str.upper()

0         UNCONFIRMED
1            VERIFIED
4            VERIFIED
5            VERIFIED
7         UNCONFIRMED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: host_identity_verified, Length: 83969, dtype: str

In [152]:
data['host_identity_verified'] = data['host_identity_verified'].str.upper()
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0,4/25/2019
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0,6/27/2018
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0,6/10/2019
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0,6/23/2019
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0,6/29/2019

# Turning False And True Into Numerical Values (0 = False, 1 = True)

In [153]:
data['instant_bookable'].apply(lambda x: 1 if x==True else 0)

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: instant_bookable, Length: 83969, dtype: int64

In [154]:
data['instant_bookable'] = data['instant_bookable'].apply(lambda x: 1 if x==True else 0)
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0,4/25/2019
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0,6/27/2018
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0,6/10/2019
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0,6/23/2019
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0,6/29/2019

 2nd Method For Boolean Conversion To Int

In [112]:
data['instant_bookable'] = data['instant_bookable'].map({True:1, False: 0}).astype('Int64')

# Reseting Index

In [155]:
data.reset_index(inplace=True)

In [158]:
check = 0
for i in data['instant_bookable']:
    check += (data['instant_bookable'] == 1).sum()

In [160]:
check

np.int64(3510995797)

# Check For Some More Transformations

### Strings to INT

In [169]:
data['price'].dtype

In [184]:
data['price'] = data["price"].str.replace("$", "")
data['price'] = data["price"].str.replace(",", "")
data['price'] = data["price"].str.replace(" ", "")

In [176]:
data['price']

0         966
1         142
2         204
3         577
4        1060
         ...
83964     822
83965     455
83966    1078
83967     103
83968     982
Name: price, Length: 83969, dtype: str

In [186]:
data.price = data.price.astype(int)

In [185]:
data.price.dtype

In [187]:
data.to_csv("CleanedData.csv")

In [188]:
pd.read_csv("CleanedData.csv")

,Unnamed: 0,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,US,0,strict,Private room,2020.0,966,$193,10.0,9.0,10/19/2021
1,1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0,5/21/2022
2,2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0,11/19/2018
3,3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,...,US,1,flexible,Entire home/apt,2013.0,577,$115,3.0,74.0,6/22/2019
4,4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,...,US,0,moderate,Private room,2009.0,1060,$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,83964,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,...,US,0,flexible,Private room,2018.0,822,$164,1.0,9.0,4/25/2019
83965,83965,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,...,US,1,moderate,Private room,2015.0,455,$91,4.0,36.0,6/27/2018
83966,83966,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,...,US,1,flexible,Private room,2020.0,1078,$216,1.0,58.0,6/10/2019
83967,83967,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,...,US,0,moderate,Private room,2007.0,103,$21,7.0,40.0,6/23/2019
83968,83968,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,...,US,1,strict,Private room,2022.0,982,$196,1.0,239.0,6/29/2019

In [192]:
data.drop(columns=['index'], inplace=True)
data.to_csv("CleanedDataWithoutIndex.csv", index=False)

In [193]:
pd.read_csv("CleanedDataWithoutIndex.csv")

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0,5/21/2022
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0,11/19/2018
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,$115,3.0,74.0,6/22/2019
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,$164,1.0,9.0,4/25/2019
83965,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,$91,4.0,36.0,6/27/2018
83966,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,$216,1.0,58.0,6/10/2019
83967,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,$21,7.0,40.0,6/23/2019
83968,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0,6/29/2019